language: go

go:
  - 1.1

before_install:
  - sudo apt-add-repository ppa:ubuntugis/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq libgeos

script: go test -v ./...
notifications:
  email:
    - warrenwyf@gmail.com
